[project]
name = "py-asm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13.3"
dependencies = [
    "numpy>=2.2.5",
]

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
]
